// Generated by CoffeeScript 1.7.1
(function() {
  var app, express, name, port, request, _i, _len, _ref;

  process.title = process.env.NAME || "static";

  express = require('express');

  request = require('request');

  app = express();

  app.use(express.logger());

  app.use('/_check', function(req, res) {
    return res.send('OK');
  });

  app.use(require("stylus").middleware({
    src: "" + __dirname + "/styles",
    dest: "" + __dirname + "/public",
    compress: true
  }));

  app.use(express["static"]("" + __dirname + "/public"));

  _ref = ['about', 'help', 'privacy', 'cookies', 'terms'];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    name = _ref[_i];
    app.use("/" + name, (function(name) {
      return function(req, res) {
        return res.redirect("/" + name + ".html");
      };
    })(name));
  }

  app.use(express.json());

  app.use(express.urlencoded());

  app.post('/request-demo', function(req, res, next) {
    console.log('DEMO REQUEST', req.body);
    request.post('https://zapier.com/hooks/catch/7bptl,7b72c/', {
      json: req.body
    }, function(err, res, body) {
      return console.log('Zapier response', body);
    });
    return res.redirect('/signup-confirmed.html');
  });

  port = process.env.PORT || 4000;

  app.listen(port);

  console.log("Listening on port " + port);

}).call(this);
